# Generated by Django 2.0.2 on 2018-02-24 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Moment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=20)),
                ('content', models.CharField(max_length=200)),
                ('user_name', models.CharField(max_length=20)),
            ],
        ),
    ]
